export default {
    products: [
      {
        _id: "1",
        name: 'bag1',
        category: 'bag',
        image1: '/images/bag1.png',
        image2: '/images/bag2.png',
        image3: '/images/bag3.png',
        price: 60,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6

      },
      {
        _id: '2',
        name: 'bag2',
        category: 'bag',
        image1: '/images/bag4.png',
        image2: '/images/bag5.png',
        image3: '/images/bag6.png',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 0
      },
      {
        _id: '3',
        name: 'bag3',
        category: 'bag',
        image1: '/images/bag7.png',
        image2: '/images/bag8.png',
        image3: '/images/bag9.png',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, {
        _id: '4',
        name: 'bag4',
        category: 'bag',
        image1: '/images/bag10.png',
        image2: '/images/bag11.png',
        image3: '/images/bag12.png',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, {
        _id: '5',
        name: 'Shirt1',
        category: 'shirt',
        image1: '/images/bag13.png',
        image2: '/images/bag14.png',
        image3: '/images/bag15.png',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, {
        _id: '6',
        name: 'bag1',
        category: 'bag',
        image1: '/images/bag1.png',
        image2: '/images/bag2.png',
        image3: '/images/bag3.png',
        price: 60,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, {
        _id: '7',
        name: 'craft1',
        category: 'craft',
        image1: '/images/bag1.png',
        image2: '/images/bag2.png',
        image3: '/images/bag3.png',
        price: 60,
        brand: ' Nagano',
        rating: 4.5,
        numReviews: 10,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, {
        _id: '8',
        name: 'craft2',
        category: 'craft',
        image1: '/images/bag1.png',
        image2: '/images/bag2.png',
        image3: '/images/bag3.png',
        price: 60,
        brand: ' Nagano',
        rating: 4.5,
        numReviews: 10,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, {
        _id: '9',
        name: 'craft3',
        category: 'craft',
        image1: '/images/bag1.png',
        image2: '/images/bag2.png',
        image3: '/images/bag3.png',
        price: 60,
        brand: ' Nagano',
        rating: 4.5,
        numReviews: 10,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, {
        _id: '10',
        name: 'craft4',
        category: 'craft',
        image1: '/images/bag1.png',
        image2: '/images/bag2.png',
        image3: '/images/bag3.png',
        price: 60,
        brand: ' Nagano',
        rating: 4.5,
        numReviews: 10,
        explanation1: "good!",
        explanation2: "nice",
        explanation3: "Greate!",
        countInStack: 6
      }, 
    ]
  }

  